version: '3.7'

services:
  interface:
    build: ./interface
    ports:
      - "8000:8000"
    volumes:
      - ./interface/src:/var/www/html
    depends_on:
      - database


  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - ./logs:/var/logs
        - ./database/sql:/opt/sql


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@andifes.br"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    volumes:
      - ./database/config/pgadmin-server.json:/pgadmin4/servers.json
    depends_on:
      - database
