name: Create DB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker Compose Up
      run: |
        sudo mkdir /var/logs && sudo chmod 777 /var/logs && \
        sudo chown -R /var/logs && \
        docker-compose -f docker-compose.yml up

    - name: Shutdown containers
      run: |
        docker-compose -f docker-compose.yml down
